### ISSUE TITLE
Unhandled exception when running commands

### ISSUE THREAD

**Issue by jordanbcooper** [indilo53/gtautil#1]
Trying to use find --position (but any command causes this) and get:

```
Unhandled Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at GTAUtil.Program.GetDLCList()
   at GTAUtil.Program.Init(String[] args)
   at GTAUtil.Program.<>c__DisplayClass10_0.<HandleFindOptions>b__0(FindOptions opts, GenericOptions gOpts)
   at GTAUtil.CommandLine.Parse[T](String[] args, Action`2 callback)
   at GTAUtil.Program.HandleFindOptions(String[] args)
   at GTAUtil.Program.Main(String[] args)
```

**Comment by jordanbcooper** [comment]
@indilo53
