### ISSUE TITLE
help please 

### ISSUE THREAD

**Issue by darkserene** [indilo53/gtautil#26]
so i followed a video on streaming the custom content to my fivem server and everything to go fine untill i put in the gtautil genpeddefs --input ClothingFiles --output CustomClothing --reserve 200 --reserveprops 200 --fivem then it comes up with this in the cmd Unhandled Exception: System.IO.FileNotFoundException: Could not find file 'ClothingFiles\mp_f_freemode_01\components\hair\1\0.ytd'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at GTAUtil.Program.GenPedDefs_CreateComponentFiles_FiveM(GenPedDefsOptions opts, String targetFileName, KeyValuePair`2 entry, Int32 textureCount)
   at GTAUtil.Program.<>c__DisplayClass27_0.<HandleGenPedDefsOptions>b__0(GenPedDefsOptions opts, GenericOptions gOpts)
   at GTAUtil.CommandLine.Parse[T](String[] args, Action`2 callback)
   at GTAUtil.Program.Main(String[] args)
please help im so confused

**Comment by YoussefAhmed00** [comment]
i need help in the same issus

**Comment by darkserene** [comment]
hey [YoussefAhmed00](https://github.com/YoussefAhmed00) 

so i figured out the issue in the videeo he only talks about the one clothing he says to create a folder and call it zero and then depending on how many ytds there are you change the name to 0 then 1 2 3 4 5 etc but what he dosent explain is in the second item you wish to add in the folder 1 call the other ytds 012345 like so in the video he says to go by the number of the file but there must always be a zero in the file hope this helps let me know
