### ISSUE TITLE
Illegal Characters error with over 27 ytd's

### ISSUE THREAD

**Issue by rubbertoe98** [indilo53/gtautil#7]
D:\CMGFiveM\WiP17\Harrods>gtautil genpeddefs --input project --output build --reserve 200 --reserveprops 200 --fivem
Loading cache
Loading DLC list
Loading file tree
project\mp_m_freemode_01

Unhandled Exception: System.ArgumentException: Illegal characters in path.
   at System.IO.LongPathHelper.Normalize(String path, UInt32 maxPathLength, Boolean checkInvalidCharacters, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at GTAUtil.Program.GenPedDefs_CreateComponentFiles_FiveM(GenPedDefsOptions opts, String targetFileName, KeyValuePair`2 entry, Int32 textureCount)
   at GTAUtil.Program.<>c__DisplayClass27_0.<HandleGenPedDefsOptions>b__0(GenPedDefsOptions opts, GenericOptions gOpts)
   at GTAUtil.CommandLine.Parse[T](String[] args, Action`2 callback)
   at GTAUtil.Program.Main(String[] args)

Getting that error when importing over 27 ytd's, figured it out because 26 is fine then add one more and you get this error. Also tried different 27th ytd's and same issue.

**Comment by indilo53** [comment]
Yes because they are generated like R* do with alphabet letters, You have to duplicate the model, at least, I don't know another way.

**Comment by rubbertoe98** [comment]
Oh ok so 27 is the max?

**Comment by indilo53** [comment]
26, from a to z

**Comment by rubbertoe98** [comment]
Ok np, thanks a lot for the quick reply!

**Comment by MonoChirito** [comment]
I have 36.... any ideas? or what do you mean with duplicating the models? sry if im stooopid
